services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    expose:
      - 6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: frontend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"  # Map host port 3000 to container port 3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Mount logs directory to container
    depends_on:
      - redis